# .travis.yml
rvm:
  #- 1.9.3
  - 2.2.0
gemfile:
  - Gemfile
  - gemfiles/minitest4-0-0.gemfile
  - gemfiles/minitest5-0-8.gemfile
  - gemfiles/minitest5-3-3.gemfile
  - gemfiles/minitest5-7-0.gemfile
before_script:
  - git config --global user.email "luke.gru@gmail.com" && git config --global user.name Luke
script:
  - bundle exec rake test
